spring:
    application:
        name: bookmanage_
    datasource:
        url: jdbc:mysql://localhost:3306/booksystem?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root
    jackson:
        date-format: yyyy-MM-dd
        time-zone: GMT+8
